name: Build and Deploy to Firebase/Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Apache Tomcat
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.1/bin/apache-tomcat-9.0.1.tar.gz
        tar -xzf apache-tomcat-9.0.1.tar.gz
        sudo mv apache-tomcat-9.0.1 /opt/tomcat
        sudo chmod +x /opt/tomcat/bin/*.sh

    - name: Deploy to Tomcat
      run: |
        sudo cp -r * /opt/tomcat/webapps/
        /opt/tomcat/bin/startup.sh

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/photography-web-usermgr:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/photography-web-usermgr:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy photography-web-usermgr \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/photography-web-usermgr:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

    - name: Set up Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy Firebase configuration
      run: |
        firebase use ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
        firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}name: Build and Deploy to Firebase/Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Apache Tomcat
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.1/bin/apache-tomcat-9.0.1.tar.gz
        tar -xzf apache-tomcat-9.0.1.tar.gz
        sudo mv apache-tomcat-9.0.1 /opt/tomcat
        sudo chmod +x /opt/tomcat/bin/*.sh

    - name: Deploy to Tomcat
      run: |
        sudo cp -r * /opt/tomcat/webapps/
        /opt/tomcat/bin/startup.sh

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/photography-web-usermgr:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/photography-web-usermgr:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy photography-web-usermgr \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/photography-web-usermgr:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

    - name: Set up Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy Firebase configuration
      run: |
        firebase use ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
        firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
